import { createClient, OAuthStrategy } from 'https://esm.sh/@wix/sdk@1.21.16'; import { functions } from 'https://esm.sh/@wix/http-functions';
const moduleInfo={mensajeria:{title:'Mensajería',text:'Canal de comunicación y avisos para residentes.'},orientacion:{title:'Orientación',text:'Guías prácticas para residentes.'},documentacion:{title:'Documentación',text:'Consulta de reglamentos, formatos y documentos relevantes.'},programacion:{title:'Programación',text:'Agenda de eventos, actividades y fechas relevantes.'},reportes:{title:'Reportes',text:'Registro y seguimiento de situaciones que requieren atención.'},visitantes:{title:'Visitantes',text:'Preautorización de entrada de visitantes.'}};
const AUTH={clientId:'2a7eb7cd-240a-422b-9fe2-10f5dec36b5e',redirectUri:'https://residencial.scad.mx/',authorizationFunction:'resAuthorization',requestFunction:'resSolicitudAcceso'},STORAGE={oauthData:'scad_residencial_wix_oauth_data',tokens:'scad_residencial_wix_tokens'}; const storedTokens=(()=>{try{return JSON.parse(localStorage.getItem(STORAGE.tokens)||'null')}catch{return null}})(); const wixClient=createClient({auth:OAuthStrategy({clientId:AUTH.clientId,...(storedTokens?{tokens:storedTokens}:{})}),modules:{functions}});
const $=id=>document.getElementById(id),authView=$('authView'),appView=$('appView'),adminView=$('adminView'),usersView=$('usersView'),adminSection=$('adminSection'),authNote=$('authNote'),loginBtn=$('loginBtn'),registerBtn=$('registerBtn'),accessSheet=$('accessSheet'),accessForm=$('accessForm'),accessStatus=$('accessStatus'),requestAccessBtn=$('requestAccessBtn'); let currentUser=null;
function isAdministrator(u){return String(u?.rolResidencial||'').trim().toLowerCase()==='administrador'} function showView(view){[authView,appView,adminView,usersView].forEach(v=>v.hidden=v!==view)}
function setAuthenticated(user){currentUser=user;const name=user?.nombreCompleto||user?.nombre||'Residente';$('residentName').textContent=name;$('residentMeta').textContent=user?.rolResidencial||'Usuario autorizado';$('residentAvatar').textContent=name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'R';adminSection.hidden=!isAdministrator(user);showView(appView)}
function setLoggedOut(message=''){currentUser=null;adminSection.hidden=true;showView(authView);loginBtn.disabled=false;registerBtn.disabled=false;if(message)authNote.textContent=message}
function openAccessState(type){showView(null);accessStatus.textContent='';accessForm.hidden=type!=='NEW';const states={NEW:['Cuenta no activada','Tu cuenta Wix está identificada, pero todavía no tienes acceso a SCaD Residencial. Envía tu solicitud para revisión de la administración.'],PENDING:['Solicitud en revisión','Tu solicitud de acceso ya fue registrada y está pendiente de autorización por la administración.'],SUSPENDED:['Acceso suspendido','Tu usuario está registrado, pero actualmente no tiene acceso a SCaD Residencial. Contacta a la administración.'],BAJA:['Acceso no disponible','Este usuario no tiene acceso vigente a SCaD Residencial. Contacta a la administración.']};[$('accessTitle').textContent,$('accessText').textContent]=states[type];accessSheet.classList.add('open')}
function closeAccessSheet(){accessSheet.classList.remove('open')} function clearCallback(){if(location.href!==AUTH.redirectUri)history.replaceState({},document.title,AUTH.redirectUri)} function hasCallback(){const q=new URLSearchParams(location.search),h=new URLSearchParams(location.hash.replace(/^#/,''));return q.has('code')||q.has('error')||h.has('code')||h.has('error')}
async function startWixLogin(){try{loginBtn.disabled=registerBtn.disabled=true;authNote.textContent='Conectando con Wix Members…';const d=await wixClient.auth.generateOAuthData(AUTH.redirectUri,location.href);localStorage.setItem(STORAGE.oauthData,JSON.stringify(d));const r=await wixClient.auth.getAuthUrl(d),url=typeof r==='string'?r:r?.authUrl;if(!url)throw Error();location.assign(url)}catch(e){console.error(e);setLoggedOut('No fue posible iniciar la autenticación con Wix.')}}
async function completeOAuthCallback(){if(!hasCallback())return{handled:false,ok:false};try{const p=await wixClient.auth.parseFromUrl();if(p?.error||!p?.code||!p?.state)throw Error(p?.errorDescription||'OAuth');const saved=localStorage.getItem(STORAGE.oauthData);if(!saved)throw Error('OAUTH_DATA_NOT_FOUND');const tokens=await wixClient.auth.getMemberTokens(p.code,p.state,JSON.parse(saved));wixClient.auth.setTokens(tokens);localStorage.setItem(STORAGE.tokens,JSON.stringify(tokens));localStorage.removeItem(STORAGE.oauthData);clearCallback();return{handled:true,ok:true}}catch(e){console.error(e);clearCallback();setLoggedOut('Wix devolvió la autenticación, pero no fue posible completar la sesión.');return{handled:true,ok:false}}}
async function validateAuthorizedUser(){if(!(await wixClient.auth.loggedIn()))return setLoggedOut('Inicia sesión para habilitar los módulos de SCaD Residencial.');try{const response=await wixClient.functions.get(AUTH.authorizationFunction),data=await response.json();if(data?.authorized&&data?.user){closeAccessSheet();return setAuthenticated(data.user)}const reason=data?.reason||'';if(reason==='MEMBER_NOT_IN_RES_USUARIOS')return openAccessState('NEW');if(reason==='USER_PENDING')return openAccessState('PENDING');if(reason==='USER_SUSPENDED'||reason==='USER_INACTIVE')return openAccessState('SUSPENDED');if(reason==='USER_BAJA')return openAccessState('BAJA');setLoggedOut('No fue posible determinar el estado de autorización de tu cuenta.')}catch(e){console.error(e);setLoggedOut('No fue posible validar la autorización en este momento.')}}
accessForm.addEventListener('submit',async e=>{e.preventDefault();requestAccessBtn.disabled=true;accessStatus.textContent='Registrando solicitud…';try{const payload={nombreCompleto:$('requestName').value.trim(),telefono:$('requestPhone').value.trim(),vivienda:$('requestHousing').value.trim()};const response=await wixClient.functions.post(AUTH.requestFunction,{headers:{'Content-Type':'application/json'},params:new URLSearchParams(),body:JSON.stringify(payload)}),data=await response.json();if(!data?.ok)throw Error();openAccessState('PENDING')}catch{accessStatus.textContent='No fue posible registrar la solicitud. Intenta nuevamente.'}finally{requestAccessBtn.disabled=false}});
$('openAdminBtn').addEventListener('click',()=>{if(isAdministrator(currentUser))showView(adminView)});$('adminBack').addEventListener('click',()=>showView(appView));$('openUsersBtn').addEventListener('click',()=>{if(isAdministrator(currentUser))showView(usersView)});$('usersBack').addEventListener('click',()=>showView(adminView));
loginBtn.addEventListener('click',startWixLogin);registerBtn.addEventListener('click',startWixLogin);$('accessClose').addEventListener('click',closeAccessSheet);const sheet=$('moduleSheet');document.querySelectorAll('[data-module]').forEach(b=>b.addEventListener('click',()=>{const i=moduleInfo[b.dataset.module];if(!i)return;$('sheetTitle').textContent=i.title;$('sheetText').textContent=i.text;sheet.classList.add('open')}));const closeSheet=()=>sheet.classList.remove('open');$('sheetClose').onclick=closeSheet;$('sheetAction').onclick=closeSheet;
document.querySelectorAll('.status-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.status-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active')}));
(async()=>{const c=await completeOAuthCallback();if(!c.handled||c.ok)await validateAuthorizedUser()})();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));