import { createClient, OAuthStrategy } from 'https://esm.sh/@wix/sdk@1.21.16';
import { functions } from 'https://esm.sh/@wix/http-functions';
const CLIENT_ID='2a7eb7cd-240a-422b-9fe2-10f5dec36b5e',TOKENS_KEY='scad_residencial_wix_tokens';
const stored=(()=>{try{return JSON.parse(localStorage.getItem(TOKENS_KEY)||'null')}catch{return null}})();
const client=createClient({auth:OAuthStrategy({clientId:CLIENT_ID,...(stored?{tokens:stored}:{})}),modules:{functions}});
const FN={list:'resAdminDocumentos',save:'resAdminDocumentoGuardar',state:'resAdminDocumentoEstado',upload:'resAdminDocumentoUploadUrl',groups:'resAdminGrupos',users:'resAdminGrupoUsuarios'};
const $=id=>document.getElementById(id);let docs=[],groups=[],users=[],activeDoc=null,selectedUser=null,selectedFile=null;
const css=document.createElement('link');css.rel='stylesheet';css.href='documents.css';document.head.appendChild(css);
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function getFn(n){const r=await client.functions.get(n);return r.json()}
async function postFn(n,p){const r=await client.functions.post(n,{headers:{'Content-Type':'application/json'},params:new URLSearchParams(),body:JSON.stringify(p)});return r.json()}
function hideViews(show){['authView','appView','adminView','usersView','groupsView','documentsAdminView'].forEach(id=>{const e=$(id);if(e)e.hidden=id!==show})}
function msg(t){$('docStatusMsg').textContent=t||''}
function inject(){const menu=$('adminView')?.querySelector('.admin-menu');if(!menu||$('openDocumentsAdminBtn'))return;menu.insertAdjacentHTML('beforeend','<button class="admin-card" id="openDocumentsAdminBtn"><span class="admin-card-icon">📄</span><span><strong>Documentación</strong><small>Documentos, permisos y disponibilidad</small></span><span class="module-arrow">›</span></button>');$('adminView').insertAdjacentHTML('afterend','<section id="documentsAdminView" hidden><div class="view-head"><button class="back-btn" id="docsBack">‹</button><div><span class="view-kicker">ADMINISTRACIÓN</span><h1>Documentación</h1></div></div><div class="docs-summary"><span>Documentos registrados</span><strong id="docsCount">0</strong></div><button class="primary-btn docs-new" id="newDocBtn" type="button">+ Nuevo documento</button><div id="docsList" class="docs-list"></div></section>');document.body.insertAdjacentHTML('beforeend',`<div class="sheet" id="docSheet"><div class="sheet-panel doc-panel"><button class="sheet-close" id="docClose">×</button><p class="eyebrow">DOCUMENTO</p><h2 id="docSheetTitle">Nuevo documento</h2><form id="docForm" class="access-form"><input id="docId" type="hidden"/><label>Título<input id="docTitle" maxlength="140" required/></label><label>Descripción<input id="docDescription" maxlength="500"/></label><div class="doc-row"><label>Categoría<input id="docCategory" maxlength="80"/></label><label>Fecha del documento<input id="docDate" type="date"/></label></div><label>Archivo PDF<input id="docFile" type="file" accept="application/pdf,.pdf"/></label><div id="docCurrentFile" class="doc-file-current"></div><p class="doc-note">Selecciona un PDF. Al guardar se cargará automáticamente a Multimedia de Wix.</p><label class="doc-check"><input id="docDownload" type="checkbox"/> Permitir descarga</label><div class="doc-audience-box"><label>Acceso<select id="docAudienceType" class="doc-select"><option value="TODOS">Todos</option><option value="ROL">Por rol</option><option value="USUARIO">Usuario</option><option value="GRUPO">Grupo</option></select></label><div id="docAudienceValue"></div></div><button class="primary-btn" id="docSaveBtn" type="submit">Guardar documento</button></form><p class="access-status" id="docStatusMsg"></p></div></div>`);$('openDocumentsAdminBtn').onclick=loadDocs;$('docsBack').onclick=()=>hideViews('adminView');$('newDocBtn').onclick=newDoc;$('docClose').onclick=()=>$('docSheet').classList.remove('open');$('docAudienceType').onchange=renderAudience;$('docFile').onchange=e=>{selectedFile=e.target.files?.[0]||null;renderFile()};$('docForm').onsubmit=saveDoc;document.querySelector('.app-footer span').textContent='v0.24'}
function audienceText(d){if(d.tipoAudiencia==='TODOS')return'Todos';if(d.tipoAudiencia==='ROL')return`Rol: ${d.audienciaNombre||d.valorAudiencia}`;if(d.tipoAudiencia==='GRUPO')return`Grupo: ${d.audienciaNombre||d.valorAudiencia}`;if(d.tipoAudiencia==='USUARIO')return`Usuario: ${d.audienciaNombre||'asignado'}`;return'Sin audiencia'}
function renderDocs(){$('docsCount').textContent=String(docs.length);$('docsList').innerHTML=docs.length?docs.map(d=>`<article class="doc-card"><button class="doc-open" data-doc="${esc(d.documentoId)}"><span class="doc-icon">📄</span><span class="doc-copy"><strong>${esc(d.titulo)}</strong><small>${esc(d.categoria||'Sin categoría')} · ${esc(audienceText(d))}</small><em>${d.descargable?'Descargable':'Sólo consulta'}</em></span><span class="doc-state ${d.activo?'on':''}">${d.activo?'Activo':'Inactivo'}</span></button><button class="doc-toggle" data-toggle-doc="${esc(d.documentoId)}" data-active="${d.activo?'1':'0'}">${d.activo?'Desactivar':'Activar'}</button></article>`).join(''):'<div class="empty-state"><strong>Sin documentos</strong><span>Registra el primer PDF.</span></div>';document.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>openDoc(b.dataset.doc));document.querySelectorAll('[data-toggle-doc]').forEach(b=>b.onclick=()=>toggleDoc(b.dataset.toggleDoc,b.dataset.active!=='1'))}
async function loadDocs(){hideViews('documentsAdminView');$('docsList').innerHTML='<div class="empty-state"><strong>Cargando…</strong></div>';try{const[d,g,u]=await Promise.all([getFn(FN.list),getFn(FN.groups),getFn(FN.users)]);if(!d?.ok)throw Error(d?.reason||'ERROR');docs=d.documentos||[];groups=g?.grupos||[];users=u?.usuarios||[];renderDocs()}catch(e){console.error(e);$('docsList').innerHTML='<div class="empty-state"><strong>No fue posible cargar Documentación</strong><span>Verifica las funciones publicadas en Wix.</span></div>'}}
function renderFile(){const box=$('docCurrentFile');if(selectedFile){box.textContent=`Seleccionado: ${selectedFile.name}`;return}box.textContent=activeDoc?.nombreArchivo?`Archivo actual: ${activeDoc.nombreArchivo}`:''}
function resetForm(){selectedUser=null;selectedFile=null;$('docId').value='';$('docTitle').value='';$('docDescription').value='';$('docCategory').value='';$('docDate').value='';$('docFile').value='';$('docDownload').checked=false;$('docAudienceType').value='TODOS';renderFile();renderAudience();msg('')}
function newDoc(){activeDoc=null;resetForm();$('docSheetTitle').textContent='Nuevo documento';$('docSheet').classList.add('open')}
function openDoc(id){activeDoc=docs.find(x=>x.documentoId===id);if(!activeDoc)return;selectedFile=null;selectedUser=activeDoc.tipoAudiencia==='USUARIO'?users.find(u=>u.memberId===activeDoc.valorAudiencia)||{memberId:activeDoc.valorAudiencia,nombreCompleto:activeDoc.audienciaNombre}:null;$('docId').value=activeDoc.documentoId;$('docTitle').value=activeDoc.titulo||'';$('docDescription').value=activeDoc.descripcion||'';$('docCategory').value=activeDoc.categoria||'';$('docDate').value=activeDoc.fechaDocumento||'';$('docFile').value='';$('docDownload').checked=activeDoc.descargable===true;$('docAudienceType').value=activeDoc.tipoAudiencia||'TODOS';$('docSheetTitle').textContent=activeDoc.titulo;renderFile();renderAudience();msg('');$('docSheet').classList.add('open')}
function renderAudience(){const type=$('docAudienceType').value,box=$('docAudienceValue');if(type==='TODOS'){box.innerHTML='<p class="doc-note">Visible para todos los usuarios autorizados.</p>';return}if(type==='ROL'){box.innerHTML='<label>Rol<select id="docAudienceSelect" class="doc-select"><option>Administrador</option><option>Residente</option><option>Proveedor</option><option>Invitado</option></select></label>';if(activeDoc?.tipoAudiencia==='ROL')$('docAudienceSelect').value=activeDoc.valorAudiencia;return}if(type==='GRUPO'){box.innerHTML=`<label>Grupo<select id="docAudienceSelect" class="doc-select"><option value="">Seleccionar grupo</option>${groups.filter(g=>g.activo).map(g=>`<option value="${esc(g.grupoId)}">${esc(g.nombre)}</option>`).join('')}</select></label>`;if(activeDoc?.tipoAudiencia==='GRUPO')$('docAudienceSelect').value=activeDoc.valorAudiencia;return}box.innerHTML='<label>Usuario<input id="docUserSearch" placeholder="Buscar por nombre, vivienda o correo"/></label><div id="docSelectedUser"></div><div id="docUserResults" class="doc-user-results"></div>';$('docUserSearch').oninput=renderUserSearch;if(selectedUser)renderSelectedUser()}
function renderSelectedUser(){$('docSelectedUser').innerHTML=selectedUser?`<div class="doc-selected-user">${esc(selectedUser.nombreCompleto||selectedUser.email||selectedUser.memberId)}</div>`:''}
function renderUserSearch(){const q=$('docUserSearch').value.trim().toLowerCase(),box=$('docUserResults');if(q.length<2){box.innerHTML='';return}const list=users.filter(u=>[u.nombreCompleto,u.email,u.vivienda].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,10);box.innerHTML=list.map(u=>`<button type="button" class="doc-user-option" data-doc-user="${esc(u.memberId)}"><strong>${esc(u.nombreCompleto||'Usuario')}</strong><small>${esc([u.vivienda,u.email,u.rolResidencial].filter(Boolean).join(' · '))}</small></button>`).join('');box.querySelectorAll('[data-doc-user]').forEach(b=>b.onclick=()=>{selectedUser=users.find(u=>u.memberId===b.dataset.docUser);renderSelectedUser();box.innerHTML='';$('docUserSearch').value=''})}
async function uploadPdf(file,documentoId){const meta=await postFn(FN.upload,{fileName:file.name,sizeInBytes:file.size,documentoId});if(!meta?.ok||!meta.uploadUrl)throw Error(meta?.reason||'UPLOAD_URL_ERROR');const r=await fetch(meta.uploadUrl,{method:'PUT',headers:{'Content-Type':'application/pdf'},body:file});if(!r.ok)throw Error('UPLOAD_ERROR');const data=await r.json();const url=data?.file?.url;if(!url)throw Error('UPLOAD_RESPONSE_ERROR');return{documentoId:meta.documentoId,archivoUrl:url,nombreArchivo:meta.fileName}}
async function saveDoc(e){e.preventDefault();const type=$('docAudienceType').value;let value='';if(type==='ROL'||type==='GRUPO')value=$('docAudienceSelect')?.value||'';if(type==='USUARIO')value=selectedUser?.memberId||'';if(type!=='TODOS'&&!value){msg('Selecciona la audiencia.');return}if(selectedFile&&selectedFile.type&&selectedFile.type!=='application/pdf'){msg('El archivo debe ser PDF.');return}if(!activeDoc&&!selectedFile){msg('Selecciona el archivo PDF.');return}msg(selectedFile?'Cargando PDF…':'Guardando…');$('docSaveBtn').disabled=true;try{let documentoId=$('docId').value.trim(),archivoUrl=activeDoc?.archivoUrl||'',nombreArchivo=activeDoc?.nombreArchivo||'';if(selectedFile){const up=await uploadPdf(selectedFile,documentoId);documentoId=up.documentoId;archivoUrl=up.archivoUrl;nombreArchivo=up.nombreArchivo;msg('PDF cargado. Guardando documento…')}const payload={documentoId,titulo:$('docTitle').value.trim(),descripcion:$('docDescription').value.trim(),categoria:$('docCategory').value.trim(),archivoUrl,nombreArchivo,fechaDocumento:$('docDate').value,orden:activeDoc?.orden??docs.length,descargable:$('docDownload').checked,tipoAudiencia:type,valorAudiencia:value};const d=await postFn(FN.save,payload);if(!d?.ok)throw Error(d?.reason||'ERROR');msg('Documento guardado.');$('docSheet').classList.remove('open');await loadDocs()}catch(e){console.error(e);msg('No fue posible guardar el documento.')}finally{$('docSaveBtn').disabled=false}}
async function toggleDoc(id,activo){try{const d=await postFn(FN.state,{documentoId:id,activo});if(!d?.ok)throw Error();await loadDocs()}catch(e){alert('No fue posible cambiar el estado del documento.')}}
inject();