import { createClient,OAuthStrategy } from 'https://esm.sh/@wix/sdk@1.21.16';
import { functions } from 'https://esm.sh/@wix/http-functions';
const $=id=>document.getElementById(id);
const TOKENS_KEY='scad_residencial_wix_tokens';
const SESSION_KEY='scad_residencial_session_id';
const CLIENT_ID='2a7eb7cd-240a-422b-9fe2-10f5dec36b5e';
const API_BASE='https://www.scad.mx/_functions';
let profileUser=null,photoPayload=null;
function tokens(){try{return JSON.parse(localStorage.getItem(TOKENS_KEY)||'null')}catch{return null}}
const client=createClient({auth:OAuthStrategy({clientId:CLIENT_ID,...(tokens()?{tokens:tokens()}:{})}),modules:{functions}});
function syncTokens(){const t=tokens();if(t)try{client.auth.setTokens(t)}catch{}}
function initials(name=''){return String(name||'R').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'R'}
function normalizeWixImageUrl(value){const raw=String(value||'').trim();if(!raw)return'';if(/^https?:\/\//i.test(raw)||/^data:image\//i.test(raw)||/^blob:/i.test(raw))return raw;if(raw.startsWith('wix:image://v1/')){const media=raw.slice('wix:image://v1/'.length).split('#')[0].split('?')[0];const mediaId=media.split('/')[0];if(mediaId)return`https://static.wixstatic.com/media/${encodeURIComponent(mediaId)}`;}return raw}
function photoUrl(v){if(!v)return'';if(typeof v==='string')return normalizeWixImageUrl(v);if(typeof v==='object')return normalizeWixImageUrl(v.url||v.src||v.fileUrl||v.imageInfo?.url||v.image?.url||'');return''}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ensureHead(){if(!document.querySelector('link[href="profile.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='profile.css';document.head.appendChild(l)}}
function ensureUI(){if($('profileSheet'))return;document.body.insertAdjacentHTML('beforeend',`<div class="sheet" id="profileSheet"><div class="sheet-panel profile-panel"><button class="sheet-close" id="profileClose" type="button">×</button><p class="eyebrow">MI IDENTIDAD</p><h2>Editar perfil</h2><div class="profile-photo-row"><div class="profile-photo-wrap"><div class="profile-photo-preview" id="profilePhotoPreview">R</div><label class="profile-photo-pencil" aria-label="Cambiar fotografía" title="Cambiar fotografía">✎<input id="profilePhotoInput" type="file" accept="image/jpeg,image/png,image/webp"></label></div><div class="profile-photo-copy"><strong>Fotografía de perfil</strong><span>JPG, PNG o WEBP · máximo 5 MB</span></div></div><form class="profile-form" id="profileForm"><label>Nombre a mostrar<input id="profileDisplayName" maxlength="60" autocomplete="name" required></label><div class="profile-email-legend"><span>Correo conectado</span><strong id="profileEmail">—</strong></div><p class="profile-status" id="profileStatus"></p><div class="profile-actions"><button class="secondary-action" id="profileCancel" type="button">Cancelar</button><button class="primary-btn" id="profileSave" type="submit">Guardar</button></div></form></div></div>`);$('profileClose').onclick=close;$('profileCancel').onclick=close;$('profileSheet').addEventListener('click',e=>{if(e.target===$('profileSheet'))close()});$('profilePhotoInput').addEventListener('change',onPhoto);$('profileForm').addEventListener('submit',save)}
function ensureEditButton(){const row=document.querySelector('.resident-row'),avatar=$('residentAvatar');if(!row||!avatar||$('profileEditBtn'))return;const b=document.createElement('button');b.id='profileEditBtn';b.className='profile-edit-btn';b.type='button';b.innerHTML='✎';b.setAttribute('aria-label','Editar perfil');b.title='Editar perfil';avatar.insertAdjacentElement('afterend',b);b.addEventListener('click',e=>{e.stopPropagation();open(e)})}
function renderCard(u){const name=String(u?.nombreMostrar||u?.nombreCompleto||u?.nombre||'Residente').trim();const avatar=$('residentAvatar');if($('residentName'))$('residentName').textContent=name;if(!avatar)return;const src=photoUrl(u?.imagen);avatar.classList.toggle('has-photo',!!src);avatar.innerHTML=src?`<img src="${esc(src)}" alt="" onerror="this.parentElement.classList.remove('has-photo');this.parentElement.textContent='${esc(initials(name))}'">`:initials(name)}
function renderPreview(src,name){const p=$('profilePhotoPreview');if(!p)return;const url=photoUrl(src);p.innerHTML=url?`<img src="${esc(url)}" alt="Fotografía de perfil">`:initials(name)}
async function loadProfile(){syncTokens();try{const r=await client.functions.get('resAuthorization'),d=await r.json();if(d?.authorized&&d?.user){profileUser=d.user;renderCard(profileUser);ensureEditButton();const row=document.querySelector('.resident-row');if(row)row.classList.add('profile-editable')}}catch(e){console.warn('SCaD perfil:',e)}}
function open(e){if(e?.target?.closest?.('.logout-btn'))return;if(!profileUser)return;photoPayload=null;$('profilePhotoInput').value='';$('profileDisplayName').value=profileUser.nombreMostrar||profileUser.nombreCompleto||profileUser.nombre||'';$('profileEmail').textContent=profileUser.email||'Correo no disponible';$('profileStatus').textContent='';renderPreview(profileUser.imagen,$('profileDisplayName').value);$('profileSheet').classList.add('open')}
function close(){$('profileSheet')?.classList.remove('open');photoPayload=null}
function canvasDataFromFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error('FOTO_LECTURA_ERROR'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(Error('FOTO_IMAGEN_INVALIDA'));img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height));const w=Math.max(1,Math.round((img.naturalWidth||img.width)*scale)),h=Math.max(1,Math.round((img.naturalHeight||img.height)*scale));const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,w,h);let quality=.84,data=c.toDataURL('image/jpeg',quality);while(data.length>1200000&&quality>.55){quality-=.08;data=c.toDataURL('image/jpeg',quality)}resolve({mimeType:'image/jpeg',base64:data,fileName:'perfil.jpg'})};img.src=String(reader.result||'')};reader.readAsDataURL(file)})}
async function onPhoto(e){const f=e.target.files?.[0];if(!f)return;const allowed=['image/jpeg','image/png','image/webp'];if(!allowed.includes(f.type)){e.target.value='';$('profileStatus').textContent='Formato de imagen no permitido.';return}if(f.size>5*1024*1024){e.target.value='';$('profileStatus').textContent='La fotografía debe pesar máximo 5 MB.';return}$('profileStatus').textContent='Preparando fotografía…';try{photoPayload=await canvasDataFromFile(f);renderPreview(photoPayload.base64,$('profileDisplayName').value);$('profileStatus').textContent='Fotografía lista para guardar.'}catch(err){console.error(err);photoPayload=null;e.target.value='';$('profileStatus').textContent='No fue posible procesar la fotografía.'}}
function readableReason(d){const r=String(d?.reason||d?.error||'').trim();const map={NO_MEMBER_ID:'No fue posible identificar tu cuenta.',NO_SESSION_ID:'No fue posible identificar esta sesión.',SESION_NO_VALIDA:'La sesión activa ya no es válida.',USUARIO_NO_ENCONTRADO:'No se encontró el usuario.',USER_INACTIVE:'El usuario no está activo.',NOMBRE_MOSTRAR_REQUERIDO:'Captura el nombre a mostrar.',NOMBRE_MOSTRAR_MUY_LARGO:'El nombre a mostrar es demasiado largo.',FOTO_FORMATO_INVALIDO:'Formato de fotografía no permitido.',FOTO_TAMANO_INVALIDO:'La fotografía excede el tamaño permitido.',FOTO_CARGA_ERROR:'No fue posible almacenar la fotografía.',PERFIL_ACTUALIZAR_ERROR:'No fue posible actualizar el perfil.'};return map[r]||r||'No fue posible actualizar el perfil.'}
async function save(e){e.preventDefault();const name=$('profileDisplayName').value.trim();if(!name){$('profileStatus').textContent='Captura el nombre a mostrar.';return}const memberId=String(profileUser?.memberId||'').trim(),sesionId=String(localStorage.getItem(SESSION_KEY)||'').trim();if(!memberId||!sesionId){$('profileStatus').textContent='No fue posible validar la sesión activa.';return}const btn=$('profileSave');btn.disabled=true;$('profileStatus').textContent='Guardando perfil…';try{const payload={memberId,sesionId,nombreMostrar:name,...(photoPayload?{foto:photoPayload}:{})};const response=await fetch(`${API_BASE}/resPerfilActualizar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'});const d=await response.json().catch(()=>({}));if(!response.ok||d?.ok!==true){console.error('SCaD perfil backend:',response.status,d);throw Object.assign(Error(readableReason(d)),{payload:d})}profileUser={...profileUser,...d.user};renderCard(profileUser);$('profileStatus').textContent='Perfil actualizado.';setTimeout(close,500)}catch(err){console.error('SCaD perfil guardar:',err);$('profileStatus').textContent=err?.message||'No fue posible actualizar el perfil.'}finally{btn.disabled=false}}
function bind(){const row=document.querySelector('.resident-row');if(!row)return;ensureEditButton();row.addEventListener('click',open)}
ensureHead();ensureUI();bind();loadProfile();window.addEventListener('focus',loadProfile);