import { createClient,OAuthStrategy } from 'https://esm.sh/@wix/sdk@1.21.16';
import { functions } from 'https://esm.sh/@wix/http-functions';
const $=id=>document.getElementById(id);
const TOKENS_KEY='scad_residencial_wix_tokens';
const CLIENT_ID='2a7eb7cd-240a-422b-9fe2-10f5dec36b5e';
let profileUser=null,photoPayload=null;
function tokens(){try{return JSON.parse(localStorage.getItem(TOKENS_KEY)||'null')}catch{return null}}
const client=createClient({auth:OAuthStrategy({clientId:CLIENT_ID,...(tokens()?{tokens:tokens()}:{})}),modules:{functions}});
function syncTokens(){const t=tokens();if(t)try{client.auth.setTokens(t)}catch{}}
function initials(name=''){return String(name||'R').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'R'}
function photoUrl(v){if(!v)return'';if(typeof v==='string')return v;if(typeof v==='object')return v.url||v.src||v.fileUrl||'';return''}
function ensureHead(){if(!document.querySelector('link[href="profile.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='profile.css';document.head.appendChild(l)}}
function ensureUI(){if($('profileSheet'))return;document.body.insertAdjacentHTML('beforeend',`<div class="sheet" id="profileSheet"><div class="sheet-panel profile-panel"><button class="sheet-close" id="profileClose" type="button">×</button><p class="eyebrow">MI IDENTIDAD</p><h2>Editar perfil</h2><div class="profile-photo-row"><div class="profile-photo-preview" id="profilePhotoPreview">R</div><div class="profile-photo-actions"><label class="profile-photo-label">📷 Cambiar fotografía<input id="profilePhotoInput" type="file" accept="image/jpeg,image/png,image/webp"></label><span class="profile-photo-help">JPG, PNG o WEBP · máximo 5 MB</span></div></div><form class="profile-form" id="profileForm"><label>Nombre a mostrar<input id="profileDisplayName" maxlength="60" required></label><label>Correo de la cuenta conectada<input class="profile-email" id="profileEmail" type="email" readonly></label><p class="profile-email-note">Este correo identifica la cuenta con la que estás conectado.</p><p class="profile-status" id="profileStatus"></p><div class="profile-actions"><button class="secondary-action" id="profileCancel" type="button">Cancelar</button><button class="primary-btn" id="profileSave" type="submit">Guardar</button></div></form></div></div>`);$('profileClose').onclick=close;$('profileCancel').onclick=close;$('profileSheet').addEventListener('click',e=>{if(e.target===$('profileSheet'))close()});$('profilePhotoInput').addEventListener('change',onPhoto);$('profileForm').addEventListener('submit',save)}
function renderCard(u){const name=String(u?.nombreMostrar||u?.nombreCompleto||u?.nombre||'Residente').trim();const avatar=$('residentAvatar');if($('residentName'))$('residentName').textContent=name;if(!avatar)return;const src=photoUrl(u?.imagen);avatar.classList.toggle('has-photo',!!src);avatar.innerHTML=src?`<img src="${src.replace(/"/g,'&quot;')}" alt="">`:initials(name)}
function renderPreview(src,name){const p=$('profilePhotoPreview');if(!p)return;p.innerHTML=src?`<img src="${src}" alt="Fotografía de perfil">`:initials(name)}
async function loadProfile(){syncTokens();try{const r=await client.functions.get('resAuthorization'),d=await r.json();if(d?.authorized&&d?.user){profileUser=d.user;renderCard(profileUser);const row=document.querySelector('.resident-row');if(row){row.classList.add('profile-editable');row.setAttribute('role','button');row.setAttribute('tabindex','0');row.setAttribute('aria-label','Editar tarjeta de identidad')}}}catch(e){console.warn('SCaD perfil:',e)}}
function open(e){if(e?.target?.closest?.('.logout-btn'))return;if(!profileUser)return;photoPayload=null;$('profilePhotoInput').value='';$('profileDisplayName').value=profileUser.nombreMostrar||profileUser.nombreCompleto||profileUser.nombre||'';$('profileEmail').value=profileUser.email||'';$('profileStatus').textContent='';renderPreview(photoUrl(profileUser.imagen),$('profileDisplayName').value);$('profileSheet').classList.add('open')}
function close(){$('profileSheet')?.classList.remove('open');photoPayload=null}
function onPhoto(e){const f=e.target.files?.[0];if(!f)return;const allowed=['image/jpeg','image/png','image/webp'];if(!allowed.includes(f.type)){e.target.value='';$('profileStatus').textContent='Formato de imagen no permitido.';return}if(f.size>5*1024*1024){e.target.value='';$('profileStatus').textContent='La fotografía debe pesar máximo 5 MB.';return}const reader=new FileReader();reader.onload=()=>{const data=String(reader.result||'');photoPayload={mimeType:f.type,base64:data};renderPreview(data,$('profileDisplayName').value);$('profileStatus').textContent='Fotografía lista para guardar.'};reader.readAsDataURL(f)}
async function save(e){e.preventDefault();const name=$('profileDisplayName').value.trim();if(!name){$('profileStatus').textContent='Captura el nombre a mostrar.';return}const btn=$('profileSave');btn.disabled=true;$('profileStatus').textContent='Guardando perfil…';syncTokens();try{const payload={nombreMostrar:name,...(photoPayload?{foto:photoPayload}:{})};const r=await client.functions.post('resPerfilActualizar',{headers:{'Content-Type':'application/json'},params:new URLSearchParams(),body:JSON.stringify(payload)});const d=await r.json();if(!d?.ok)throw Error(d?.reason||d?.error||'PERFIL_ACTUALIZAR_ERROR');profileUser={...profileUser,...d.user};renderCard(profileUser);$('profileStatus').textContent='Perfil actualizado.';setTimeout(close,450)}catch(err){console.error(err);$('profileStatus').textContent='No fue posible actualizar el perfil.'}finally{btn.disabled=false}}
function bind(){const row=document.querySelector('.resident-row');if(!row)return;row.addEventListener('click',open);row.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('.logout-btn')){e.preventDefault();open(e)}})}
ensureHead();ensureUI();bind();loadProfile();window.addEventListener('focus',loadProfile);