import { createClient, OAuthStrategy } from 'https://esm.sh/@wix/sdk@1.21.16';
import { functions } from 'https://esm.sh/@wix/http-functions';

const CLIENT_ID='2a7eb7cd-240a-422b-9fe2-10f5dec36b5e',TOKENS_KEY='scad_residencial_wix_tokens';
const stored=(()=>{try{return JSON.parse(localStorage.getItem(TOKENS_KEY)||'null')}catch{return null}})();
const client=createClient({auth:OAuthStrategy({clientId:CLIENT_ID,...(stored?{tokens:stored}:{})}),modules:{functions}});
const FN={list:'resAdminProgramacion',save:'resAdminProgramacionGuardar',state:'resAdminProgramacionEstado',groups:'resAdminGrupos',users:'resAdminGrupoUsuarios'};
const CATS=['Actividades','Servicios','Mantenimiento','Afectaciones','Otros'];
const $=id=>document.getElementById(id);
let items=[],groups=[],users=[],activeItem=null,selectedUser=null,currentMonth=new Date();currentMonth.setDate(1);

const css=document.createElement('link');css.rel='stylesheet';css.href='programming.css';document.head.appendChild(css);
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function catClass(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-')}
async function getFn(n){const r=await client.functions.get(n);return r.json()}
async function postFn(n,p){const r=await client.functions.post(n,{headers:{'Content-Type':'application/json'},params:new URLSearchParams(),body:JSON.stringify(p)});return r.json()}
function hideViews(show){['authView','appView','adminView','usersView','groupsView','documentsAdminView','programmingAdminView'].forEach(id=>{const e=$(id);if(e)e.hidden=id!==show})}
function dateInputValue(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';const p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function timeInputValue(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function audienceText(p){if(p.tipoAudiencia==='TODOS')return'Todos';if(p.tipoAudiencia==='ROL')return`Rol: ${p.audienciaNombre||p.valorAudiencia}`;if(p.tipoAudiencia==='GRUPO')return`Grupo: ${p.audienciaNombre||p.valorAudiencia}`;if(p.tipoAudiencia==='USUARIO')return`Usuario: ${p.audienciaNombre||'asignado'}`;return'Sin audiencia'}
function fmt(v,allDay=false){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return new Intl.DateTimeFormat('es-MX',allDay?{dateStyle:'medium'}:{dateStyle:'medium',timeStyle:'short'}).format(d)}
function localIso(date,time,allDay,end=false){if(!date)return'';const t=allDay?(end?'23:59':'00:00'):(time||'00:00');const d=new Date(`${date}T${t}:00`);return d.toISOString()}

function inject(){
 const menu=$('adminView')?.querySelector('.admin-menu');if(!menu||$('openProgrammingAdminBtn'))return;
 menu.insertAdjacentHTML('beforeend','<button class="admin-card" id="openProgrammingAdminBtn"><span class="admin-card-icon">📅</span><span><strong>Programación</strong><small>Calendario, actividades y afectaciones previstas</small></span><span class="module-arrow">›</span></button>');
 $('adminView').insertAdjacentHTML('afterend',`<section id="programmingAdminView" hidden><div class="view-head"><button class="back-btn" id="progBack">‹</button><div><span class="view-kicker">ADMINISTRACIÓN</span><h1>Programación</h1></div></div><div class="prog-toolbar"><select id="progFilter" aria-label="Filtrar por categoría"><option value="">▦ Todas las categorías</option>${CATS.map(c=>`<option>${c}</option>`).join('')}</select><button class="primary-btn prog-new" id="newProgBtn" type="button"><span class="prog-new-icon">＋</span><span class="prog-new-label">Programación</span></button></div><div class="prog-calendar"><div class="prog-cal-head"><button class="prog-cal-nav" id="progPrev" type="button">‹</button><strong id="progMonthTitle"></strong><button class="prog-cal-nav" id="progNext" type="button">›</button></div><div class="prog-weekdays"><span>Lun</span><span>Mar</span><span>Mié</span><span>Jue</span><span>Vie</span><span>Sáb</span><span>Dom</span></div><div class="prog-grid" id="progGrid"></div></div><div class="prog-list" id="progList"></div></section>`);
 document.body.insertAdjacentHTML('beforeend',`<div class="sheet" id="progSheet"><div class="sheet-panel prog-sheet-panel"><button class="sheet-close" id="progClose">×</button><p class="eyebrow">PROGRAMACIÓN</p><h2 id="progSheetTitle">Nueva programación</h2><form id="progForm" class="prog-form"><input id="progId" type="hidden"/><div class="prog-core-grid"><label>✎ Título<input id="progTitle" maxlength="140" required/></label><label>◆ Clasificación<select id="progCategory">${CATS.map(c=>`<option>${c}</option>`).join('')}</select></label></div><label>≡ Descripción<textarea id="progDescription" maxlength="1000"></textarea></label><div class="prog-location-day"><label>⌖ Ubicación<input id="progLocation" maxlength="140"/></label><label class="prog-check"><input id="progAllDay" type="checkbox"/><span>◷ Todo el día</span></label></div><div class="prog-datetime"><div class="prog-datetime-row"><span class="prog-row-label">▶ Inicio</span><input id="progStartDate" type="date" required aria-label="Fecha de inicio"/><input id="progStartTime" type="time" aria-label="Hora de inicio"/></div><div class="prog-datetime-row"><span class="prog-row-label">■ Término</span><input id="progEndDate" type="date" aria-label="Fecha de término"/><input id="progEndTime" type="time" aria-label="Hora de término"/></div></div><div class="prog-audience"><label>👥 Acceso<select id="progAudienceType"><option value="TODOS">Todos</option><option value="ROL">Por rol</option><option value="USUARIO">Usuario</option><option value="GRUPO">Grupo</option></select></label><div id="progAudienceValue"></div></div><div class="prog-form-footer"><p class="prog-status" id="progStatus"></p><button class="primary-btn" id="progSaveBtn" type="submit">✓ Guardar</button></div></form></div></div>`);
 $('openProgrammingAdminBtn').onclick=loadAll;$('progBack').onclick=()=>hideViews('adminView');$('newProgBtn').onclick=newItem;$('progClose').onclick=()=>$('progSheet').classList.remove('open');$('progPrev').onclick=()=>{currentMonth.setMonth(currentMonth.getMonth()-1);renderCalendar()};$('progNext').onclick=()=>{currentMonth.setMonth(currentMonth.getMonth()+1);renderCalendar()};$('progFilter').onchange=()=>{renderCalendar();renderList()};$('progAudienceType').onchange=renderAudience;$('progAllDay').onchange=syncAllDay;$('progForm').onsubmit=saveItem;
 const foot=document.querySelector('.app-footer span');if(foot)foot.textContent='v0.45';
}

async function loadAll(){hideViews('programmingAdminView');$('progGrid').innerHTML='<div class="prog-empty">Cargando…</div>';try{const[p,g,u]=await Promise.all([getFn(FN.list),getFn(FN.groups),getFn(FN.users)]);if(!p?.ok)throw Error(p?.reason||'PROGRAMACION_ERROR');items=p.programaciones||[];groups=g?.grupos||[];users=u?.usuarios||[];renderCalendar();renderList()}catch(e){console.error(e);$('progGrid').innerHTML='<div class="prog-empty">No fue posible cargar Programación.</div>';$('progList').innerHTML=''}}
function filtered(){const c=$('progFilter')?.value||'';return items.filter(x=>!c||x.categoria===c)}
function renderCalendar(){const title=$('progMonthTitle');if(!title)return;title.textContent=new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric'}).format(currentMonth);const y=currentMonth.getFullYear(),m=currentMonth.getMonth();const first=new Date(y,m,1),start=new Date(first);const offset=(first.getDay()+6)%7;start.setDate(first.getDate()-offset);const today=new Date();today.setHours(0,0,0,0);let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const out=d.getMonth()!==m;const dayStart=new Date(d);dayStart.setHours(0,0,0,0);const dayEnd=new Date(d);dayEnd.setHours(23,59,59,999);const events=filtered().filter(p=>{const s=new Date(p.fechaInicio),e=p.fechaFin?new Date(p.fechaFin):s;return s<=dayEnd&&e>=dayStart});html+=`<div class="prog-day ${out?'out':''} ${dayStart.getTime()===today.getTime()?'today':''}"><span class="prog-day-num">${d.getDate()}</span>${events.slice(0,3).map(p=>`<button type="button" class="prog-event cat-${catClass(p.categoria)} ${p.activo?'is-active':'inactive'}" data-prog-id="${esc(p.programacionId)}">${esc(p.titulo)}</button>`).join('')}${events.length>3?`<span class="prog-more">+${events.length-3}</span>`:''}</div>`} $('progGrid').innerHTML=html;document.querySelectorAll('.prog-event').forEach(b=>b.onclick=()=>openItem(b.dataset.progId))}
function renderList(){const list=filtered().slice().sort((a,b)=>new Date(a.fechaInicio)-new Date(b.fechaInicio));$('progList').innerHTML=list.length?list.map(p=>`<article class="prog-list-card cat-${catClass(p.categoria)} ${p.activo?'is-active':'is-inactive'}"><div class="prog-list-card-head"><div class="prog-list-copy"><strong>${esc(p.titulo)}</strong><small>◈ ${esc(p.categoria)} · ${esc(fmt(p.fechaInicio,p.todoElDia))}${p.fechaFin?` → ${esc(fmt(p.fechaFin,p.todoElDia))}`:''}</small><small>👥 ${esc(audienceText(p))}${p.ubicacion?` · ⌖ ${esc(p.ubicacion)}`:''}</small></div><span class="prog-state ${p.activo?'is-active':'is-inactive'}">${p.activo?'● Activo':'○ Inactivo'}</span></div><div class="prog-list-actions"><button type="button" data-edit-prog="${esc(p.programacionId)}">✎ Editar</button><button type="button" data-toggle-prog="${esc(p.programacionId)}" data-active="${p.activo?'1':'0'}">${p.activo?'⊘ Desactivar':'✓ Activar'}</button></div></article>`).join(''):'<div class="prog-empty">Sin programaciones registradas.</div>';document.querySelectorAll('[data-edit-prog]').forEach(b=>b.onclick=()=>openItem(b.dataset.editProg));document.querySelectorAll('[data-toggle-prog]').forEach(b=>b.onclick=()=>toggleItem(b.dataset.toggleProg,b.dataset.active!=='1'))}
function reset(){activeItem=null;selectedUser=null;$('progId').value='';$('progTitle').value='';$('progCategory').value='Actividades';$('progDescription').value='';$('progLocation').value='';$('progAllDay').checked=false;$('progStartDate').value='';$('progStartTime').value='';$('progEndDate').value='';$('progEndTime').value='';$('progAudienceType').value='TODOS';$('progStatus').textContent='';syncAllDay();renderAudience()}
function newItem(){reset();$('progSheetTitle').textContent='Nueva programación';$('progSheet').classList.add('open')}
function openItem(id){activeItem=items.find(x=>x.programacionId===id)||null;if(!activeItem)return;selectedUser=activeItem.tipoAudiencia==='USUARIO'?users.find(u=>u.memberId===activeItem.valorAudiencia)||{memberId:activeItem.valorAudiencia,nombreCompleto:activeItem.audienciaNombre}:null;$('progId').value=activeItem.programacionId;$('progTitle').value=activeItem.titulo||'';$('progCategory').value=activeItem.categoria||'Actividades';$('progDescription').value=activeItem.descripcion||'';$('progLocation').value=activeItem.ubicacion||'';$('progAllDay').checked=activeItem.todoElDia===true;$('progStartDate').value=dateInputValue(activeItem.fechaInicio);$('progStartTime').value=timeInputValue(activeItem.fechaInicio);$('progEndDate').value=dateInputValue(activeItem.fechaFin);$('progEndTime').value=timeInputValue(activeItem.fechaFin);$('progAudienceType').value=activeItem.tipoAudiencia||'TODOS';$('progSheetTitle').textContent=activeItem.titulo;syncAllDay();renderAudience();$('progStatus').textContent='';$('progSheet').classList.add('open')}
function syncAllDay(){const all=$('progAllDay').checked;$('progStartTime').hidden=all;$('progEndTime').hidden=all;document.querySelectorAll('.prog-datetime-row').forEach(row=>row.classList.toggle('all-day',all))}
function renderAudience(){const type=$('progAudienceType').value,box=$('progAudienceValue');if(type==='TODOS'){box.innerHTML='';return}if(type==='ROL'){box.innerHTML='<label>Rol<select id="progAudienceSelect"><option>Administrador</option><option>Residente</option><option>Proveedor</option><option>Invitado</option></select></label>';if(activeItem?.tipoAudiencia==='ROL')$('progAudienceSelect').value=activeItem.valorAudiencia;return}if(type==='GRUPO'){box.innerHTML=`<label>Grupo<select id="progAudienceSelect"><option value="">Seleccionar grupo</option>${groups.filter(g=>g.activo).map(g=>`<option value="${esc(g.grupoId)}">${esc(g.nombre)}</option>`).join('')}</select></label>`;if(activeItem?.tipoAudiencia==='GRUPO')$('progAudienceSelect').value=activeItem.valorAudiencia;return}box.innerHTML='<label>Usuario<input id="progUserSearch" placeholder="Buscar por nombre, vivienda o correo"/></label><div id="progSelectedUser"></div><div id="progUserResults" class="prog-user-results"></div>';$('progUserSearch').oninput=renderUserSearch;if(selectedUser)renderSelectedUser()}
function renderSelectedUser(){$('progSelectedUser').innerHTML=selectedUser?`<div class="prog-selected">✓ ${esc(selectedUser.nombreCompleto||selectedUser.email||selectedUser.memberId)}</div>`:''}
function renderUserSearch(){const q=$('progUserSearch').value.trim().toLowerCase(),box=$('progUserResults');if(q.length<2){box.innerHTML='';return}const list=users.filter(u=>[u.nombreCompleto,u.email,u.vivienda].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,10);box.innerHTML=list.map(u=>`<button type="button" class="prog-user-option" data-prog-user="${esc(u.memberId)}"><strong>${esc(u.nombreCompleto||'Usuario')}</strong><small>${esc([u.vivienda,u.email,u.rolResidencial].filter(Boolean).join(' · '))}</small></button>`).join('');box.querySelectorAll('[data-prog-user]').forEach(b=>b.onclick=()=>{selectedUser=users.find(u=>u.memberId===b.dataset.progUser);renderSelectedUser();box.innerHTML='';$('progUserSearch').value=''})}
async function saveItem(e){e.preventDefault();const type=$('progAudienceType').value;let value='';if(type==='ROL'||type==='GRUPO')value=$('progAudienceSelect')?.value||'';if(type==='USUARIO')value=selectedUser?.memberId||'';if(type!=='TODOS'&&!value){$('progStatus').textContent='Selecciona la audiencia.';return}const all=$('progAllDay').checked,startDate=$('progStartDate').value,endDate=$('progEndDate').value||startDate;if(!startDate){$('progStatus').textContent='La fecha de inicio es obligatoria.';return}let start,end;try{start=localIso(startDate,$('progStartTime').value,all,false);end=endDate?localIso(endDate,$('progEndTime').value,all,true):''}catch{$('progStatus').textContent='Fecha u hora inválida.';return}if(end&&new Date(end)<new Date(start)){$('progStatus').textContent='La fecha de término no puede ser anterior al inicio.';return}$('progSaveBtn').disabled=true;$('progStatus').textContent='Guardando…';try{const payload={programacionId:$('progId').value.trim(),titulo:$('progTitle').value.trim(),descripcion:$('progDescription').value.trim(),categoria:$('progCategory').value,fechaInicio:start,fechaFin:end,todoElDia:all,ubicacion:$('progLocation').value.trim(),activo:activeItem?activeItem.activo:true,tipoAudiencia:type,valorAudiencia:value};const d=await postFn(FN.save,payload);if(!d?.ok)throw Error(d?.reason||'ERROR');$('progSheet').classList.remove('open');await loadAll()}catch(err){console.error(err);$('progStatus').textContent=`No fue posible guardar: ${err?.message||err}`}finally{$('progSaveBtn').disabled=false}}
async function toggleItem(id,activo){try{const d=await postFn(FN.state,{programacionId:id,activo});if(!d?.ok)throw Error(d?.reason||'ERROR');await loadAll()}catch(e){console.error(e);alert('No fue posible cambiar el estado de la programación.')}}

inject();